version: '3.7'
services: 
  mongo:
    image: mongo:4-xenial
    volumes:
        - mongo_data_volume:/data/db
  yapi:
    image: azleal/yapi-app
    build:
      context: ./yapi-app
      args:
        YAPI_APP_VERSION: "1.8.1"
 #   ports:
 #      - "3000:3000"
    working_dir: /api/vendors
    depends_on:
        - mongo
    command: ["server/app.js"]
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - yapi

     
volumes:
  mongo_data_volume: